CMR 8424: Added retrieving uid and groups from EDL, filtering related…
nasa/cmr-graphql pull request #14
Opened 2022-08-18 17:33 UTC by eudoroolivares2016

… collections and duplicate collections by permitted groups

Need to clean up log and TODO statements after feedback

# Overview

### What is the feature?

This is to allow graphQl to query for related collections and duplicate collections over permitted groups which are being indexed by graphDb following the indexing changes made in https://github.com/nasa/Common-Metadata-Repository/pull/1623

### What is the Solution?

An HTTP request is made to EDL to retrieve a client's UID if a bearer token is supplied. During a query for related collections or duplicate collections which reach out to graphDb, another http request is made to EDL to retrieve the groups which that client is apart of using the uid from the context object and the client_id of the application as an environment variable. These groups are then appended to the gremlin queries as `.has()` filters that limit visibility of collections which do not include one of the permittedGroups that a client is in. Note that all clients have access to collections with a permitted group "guest". These are collections which are meant to be available to the public and are associated with acls that have user_type = guest. 

### What areas of the application does this impact?

Related collections and duplicate collections. The handler has also been altered to retrieve the uid of a client from EDL and pass that across the context object to the necessary resolvers and datasources. Tests were altered to add cases for checking that the filters are added to the gremlin query as well as for the data fetching functions. 

# Testing

### Reproduction steps

- **Environment for testing:**
- **Collection to test with:**
[populateLocalGraphDB.js.zip](https://github.com/nasa/cmr-graphql/files/9376170/populateLocalGraphDB.js.zip)

To test locally, where we can use collection objects that have permittedGroups as a property; start up a gremlin-server that has an exposed http endpoint. We can do this by using docker. Running docker run -it -p 8182:8182 tinkerpop/gremlin-server conf gremlin-server-rest-modern.yaml will start up the server and then we must
as well as altering the `gremlinPath/url` in `(src/utils/cmrGraphDb.js)` to the localhost address the gremlin server is running on. We can most quickly insert test data utilizing a populateLocalGraphDb.js script included in the PR. Usage is: `node populateLocalGraphDb.js vertex` then run the script again with the edge argument, `node populateLocalGraphDb.js vertex` in the unaltered populateLocalGraphDb.js script this places two related collections into the graph (as well as a duplicate collection) querying against these will only result in a single record being returned as one of them is in a private group and the others are in guest. This demonstrates filtering based on the permitted groups that a user is apart of against private record which the client does NOT have viewing rights.

### Attachments
Attached is a zip containing the populateLocalGraphDb.js script. Note: the most simple way to run this script will be to run it from inside of the garphQl repo (copied into the src/utils/ directory for example) as it relies on some of the node modules that the project utilizes. 

# Checklist

- [x] I have added automated tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have performed a self-review of my own
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2022-08-18 19:41 UTC, eudoroolivares2016 commented
I will need to add the environment variables should it be decided to use them into the serverless.yml and update the README accordingly. Under current PR the env variables would be: one for the URS root directory (sit, UAT, prod) and another for the client id of the application

2022-08-23 19:05 UTC, abbottry requested changes

2022-08-23 19:09 UTC, eudoroolivares2016 commented on src/resolvers/collection.js
> +      // Split granuleParams before args to allow for overwriting granuleParams
That makes alot of sense, sorry thought I was just fixing a typo!

2022-08-29 20:08 UTC, eudoroolivares2016 commented on src/graphql/handler.js
> +    if (bearerToken) {
I have put in the regex into the later commits

2022-08-29 20:09 UTC, eudoroolivares2016 commented on src/graphql/handler.js
> +      uid = await verifyEdlToken(bearerToken)
This has been changed as well as tests. Totally agree the username was a poor variable name

2022-08-29 20:09 UTC, eudoroolivares2016 commented on src/utils/verifyEdlToken.js
> +      url: `${process.env.ursRootUrl}/oauth/tokens/user?client_id=${process.env.mockClientId}&token=${edlToken}`
I altered this env variable in newest commit

2022-09-01 20:51 UTC, macrouch commented on src/utils/verifyEDLJwt.js
> +  } catch (err) {
These multiple console logs don't seem super useful, same with the valid log above. Why not just log out the error object? (if it is an object call `JSON.stringify(err)` to get a useful log message)

2022-09-01 20:51 UTC, macrouch commented on src/utils/verifyEDLJwt.js
> +      const rsaEnv = JSON.parse(process.env.edlJwk)
Does this variable name make more sense if it is called `edlJwk` instead of `rsaEnv`? Just pointing out the inconsistency in names

2022-09-01 20:51 UTC, macrouch commented on src/datasources/graphDbDuplicateCollections.js
> +    console.log('Collection was missing a doi or a shortName')
This console log feels unnecessary

2022-09-01 21:16 UTC, trevorlang approved these changes
I didn't catch anything that was not brought up in the review or in the comments already. If that is all resolved, this looks good to me. I am unavailable after today, so once Matthew and Ryan are good with this, ship it! 🚢

2022-09-02 00:29 UTC, macrouch approved these changes

2022-09-06 14:31 UTC, abbottry approved these changes

2022-09-06 14:33 UTC, macrouch approved these changes

2022-09-06 14:43 UTC, merged