MMT-2863: Added Standard Product
nasa/cmr-graphql pull request #6
Opened 2022-05-10 19:26 UTC by dmistry1

Added Standard Product

2022-05-11 17:06 UTC, abbottry requested changes
We need to ask CMR for the newest version of UMM-C as StandardProduct is only available there, that version is 1.17.0 -- this update needs to happen in serverless.yml. There is an additional issue found while testing that fails for records that have `false` as their value.

2022-05-12 17:37 UTC, macrouch approved these changes

2022-05-12 18:53 UTC, trevorlang approved these changes

2022-05-13 01:37 UTC, abbottry approved these changes

2022-05-13 12:16 UTC, merged